OverviewUI <- function(id) {
  list(
    "Inputs" = 
      list(
        ), 
    "Outputs" = 
      list(
        fluidRow(
          column(
            10,
            box(
              title ="",
              id = NS(id,"Overview"),
              height= "auto",
              width = "auto", 
              HTML(
                '<div class="overviewHeader">WHAT ARE CYTOKINES?</div>
                <p>
                Cytokines, chemokines and related factors are proteins employed by the immune system to orchestrate appropriate immune responses. 
                These proteins are key for communication among various tissues and immune cells, and for modulation of immune cell function. 
                Given their importance in COVID19, cytokines, chemokines and related immune factors were measured with a technology exclusively devoted 
                to the detection of these molecules in a quantitative fashion.
                </p>
        
                <br />
                <div class="overviewHeader">OVERVIEW</div>
                <p>
                This dashboard contains data generated from plasma using Meso Scale Discovery&reg; assays for 82 unique immune regulatory factors. 
                In the &lsquo;Effect of COVID19&rsquo; dashboard, users can explore the differences in cytokine levels between samples from those with versus without COVID19. 
                In the &lsquo;Effect of Seroconversion&rsquo; dashboard, users can explore the differences in cytokine levels between samples from COVID19 patients with low levels of seroconversion versus those with high levels of seroconversion.  
                The data are searchable by <a href="./MSD Names.pdf" target="_blank"><b>factor name</b></a> and can be filtered by age group and sex. 
                Users can select different statistical tests and adjustment method for multiple hypotheses correction. 
                A detailed description of seroconversion studies can be found in our manuscript under 
                <a href="https://www.medrxiv.org/content/10.1101/2020.12.05.20244442v1" target="_blank"><b>review</b></a>. 
                </p>
                <br />

                <div class="overviewHeader">METHODS</div>
                <p>
                Meso Scale Discovery&reg; data was generated by the <a href="https://medschool.cuanschutz.edu/immunology-immunotherapy/himsr" target="_blank"><b>Human Immune Monitoring Shared Resource of the University of Colorado</b></a> 
                using manufacturer&lsquo;s instructions. 
                </p>
          
                <br /><br />'
              )
            )
          )
        )
       
      )
  )
  
}

OverviewServer <- function(id) {
  
  moduleServer(id, function(input, output, session) {
    
     
  })
  
}